Allow some urls to be missing
scrazzz/redgifs pull request #40
Opened 2024-11-15 03:58 UTC by theintrepidfox

In practice I have found that `hd` and `poster` URLs are not always present. They are almost always present, but I can provide some IDs for cases where these are missing. Unfortunately, they are NSFW videos, so I will exclude these IDs for now. If they are of interest, let me know, and I'll leave them in a comment.

2024-11-15 07:44 UTC, scrazzz requested changes
Hey, thanks for letting me know. You can share just the ID here if you wish or in the Discord server (README file).

There is a small correction here, if you can fix it I'll merge it asap.

2024-11-15 07:44 UTC, scrazzz commented on redgifs/api.py
> +                hd=urls['hd'] if 'hd' in urls else None,
```suggestion
                hd=urls.get('hd'),
```

2024-11-15 07:44 UTC, scrazzz commented on redgifs/api.py
> +                poster=urls['poster'] if 'poster' in urls else None,
```suggestion
                poster=urls.get('poster'),
```

2024-11-15 18:33 UTC, theintrepidfox commented
Ah yes I missed the same pattern just a few lines down. No rush to merge on my account, but this is updated now.

2024-11-16 19:24 UTC, theintrepidfox commented
No "poster" url: lightgrayregalseaslug
No "hd" url: definitiveblandwasp

I'll look at the failing tests and linters later. There's a few things I'd like to contribute (mypy fixes and two other small changes I've made in other branches), but I haven't found the time.

2024-11-17 03:42 UTC, scrazzz commented
I too am busy at the moment so can't check these failing checks. Once I get the time I'll get back to this PR. Also fyi: I use pyright and not mypy (just a personal preference).

2024-11-17 11:47 UTC, scrazzz reviewed
Actually, I'll merge this right now since there are some other stuff that needs updating like the docstrings and failing checks. Thanks for submitting this PR!

2024-11-17 11:48 UTC, merged

2024-11-17 11:54 UTC, scrazzz commented
The checks are failing because this is a breaking change. Hence the old code for the CLI command needs to be updated and I'm working on that right now.

2024-11-17 12:04 UTC, scrazzz commented
> No "poster" url: lightgrayregalseaslug
> No "hd" url: definitiveblandwasp
> 
> I'll look at the failing tests and linters later. There's a few things I'd like to contribute (mypy fixes and two other small changes I've made in other branches), but I haven't found the time.

I checked this right now and found out that `poster` can be `None`. But for the 2nd ID you provided, there is an `hd` url available for that gif:
```py
GIF(id='definitiveblandwasp',
    ...
    urls=URL(sd='https://files.redgifs.com/DefinitiveBlandWasp-mobile.mp4',
             hd='https://files.redgifs.com/DefinitiveBlandWasp.mp4',  # here
             poster='https://files.redgifs.com/DefinitiveBlandWasp-poster.jpg',
             thumbnail='https://files.redgifs.com/DefinitiveBlandWasp-mobile.jpg',
             vthumbnail='https://files.redgifs.com/DefinitiveBlandWasp-mobile.mp4',
             web_url='https://redgifs.com/watch/definitiveblandwasp',
             file_url='https://api.redgifs.com/v2/gifs/definitiveblandwasp/files/DefinitiveBlandWasp.mp4',
             embed_url='https://api.redgifs.com/v2/embed/discord?name=DefinitiveBlandWasp.mp4'),
    username='brooklyn-69',
    type=1,
    avg_color='#3b2f2d')